spring.application.name=leftover-api

server.port=8080

spring.datasource.url=jdbc:mysql://localhost:3307/leftoverapi
spring.datasource.username=root
spring.datasource.password=Thisismanmad1@

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.error.include-message=always
server.error.include-binding-errors=always

pay-period.closed.queue.name=PAY_PERIOD_CLOSED_QUEUE
pay-period.exchange.name=PAY_PERIOD_EXCHANGE
pay-period.routing.key=PAY_PERIOD_CLOSED_ROUTING_KEY
